/**
 * @file src/mcp/resources.ts
 * @brief MCP resource registration for usage guidance.
 */

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";

const CODEBRAIN_USAGE_URI = "codebrain://usage";
export const CODEBRAIN_SERVER_INSTRUCTIONS = [
  "CodeBrain is a code-graph index, not a search engine. Each tool answers a different question -- pick the matching tool rather than reaching for `semantic_search` by default.",
  "",
  "Prefer MCP semantic/symbol/reference/dependency tools for architecture and impact analysis. Use `rg`/`grep` as a precision and verification complement -- exact text matches the index doesn't cover, or to confirm an indexed finding -- not as a substitute.",
  "",
  "Loop: (1) call `list_repositories` to get the `repo` string -- never guess it. (2) SEARCH FIRST: call `find_symbol name=<word>` for each domain noun in the user's question (e.g. \"polyline\", \"canvas\", \"auth\") -- lowercase, English, partial all hit. Treat the user's content words AS candidate identifiers; do not pre-judge whether they \"look like\" code names. Orientation tools (`get_file_map`, `get_module_map`) are the FALLBACK if search returns nothing -- not the first step. (3) read the result -- once `find_symbol`/`describe_node`/`get_intent` give you the shape, open only the line range that matters. (4) harvest the codebase's own identifiers from that read and use them in any follow-up codebrain query.",
  "",
  "Default first move: when the user asks \"how does X work / how do I implement X / where is Y\", the very first codebrain call after `list_repositories` should be `find_symbol name=<the main noun>`. NOT `get_file_map`. NOT `Grep`. The index does case-insensitive partial matching so the user's English nouns usually hit a real symbol on the first try.",
  "",
  "Critical: BEFORE any `Grep`/`Read`/`Glob` for code, you MUST have called at least one of `find_symbol`, `exact_symbol_search`, `semantic_search`, or `describe_node`. If you can name a symbol, file, or concept -- from the user, orientation, or a previous read -- there is always a codebrain tool that does better than Grep. Grep is for string literals in comments/config, or to verify a codebrain finding. Reading a whole file in 200-line pages is the WRONG move; call `describe_node` or `get_intent` first to get the shape, then read the specific line range.",
  "",
  "Common failure 1: agent's first move is `get_file_map path_prefix=src` instead of `find_symbol`. \"Orient before searching\" is the wrong default here -- `find_symbol` with the user's words is faster and usually hits. CORRECT: `find_symbol name=<user's noun>` first; only call `get_file_map` (no prefix) if search returned nothing.",
  "",
  "Common failure 2: agent has the user's word (\"polyline\", \"animation\", a class name), skips `find_symbol`, and Greps. CORRECT: `find_symbol name=<user-term>` first -- partial-name match is case-insensitive and often hits. Only fall back to `semantic_search` if that returns nothing.",
  "",
  "Common failure 3: agent calls `get_file_map path_prefix=src` or `path_prefix=lib`, gets the new self-correcting hint listing real top-level dirs, BUT this was already step 2 -- search should have been first. If you're reading this hint, your prior call should have been `find_symbol` instead. CORRECT order: `find_symbol` -> (only if empty) `get_file_map` with no prefix -> read.",
  "",
  "Common failure 4: agent orients with `get_file_map`, sees a relevant class name (e.g. `AnimationCanvas`), then runs `Grep AnimationCanvas` and `Read`s the file top-to-bottom. CORRECT: `exact_symbol_search name=AnimationCanvas` -> `describe_node kind=symbol` for the gist -> `extract_module_interface` or `find_symbol kind=method file=<that file>` to see its existing primitives (e.g. DrawCircle, DrawLine) -> read only the targeted lines of one analog to mirror. Never read the whole file blind.",
  "",
  "Stop rule: after 2 unproductive queries, switch tool, not keywords. Rephrasing the same words against `semantic_search` wastes calls because embeddings treat permutations as the same query.",
  "",
  "Tool selector (in priority order for typical questions):",
  "- FIRST: any user-supplied noun -> `find_symbol name=<noun>`. Try lowercase, English, partial -- the index matches case-insensitive. This is the default first call.",
  "- Exact identifier you've already seen -> `exact_symbol_search`. Concept with no name guess at all -> `semantic_search`.",
  "- Callers/refs of a symbol -> `find_references`. Call graph -> `find_call_graph`. Impact of a change -> `find_impact`.",
  "- What a file/symbol/cluster is for -> `describe_node` or `get_intent` (call BEFORE reading the file).",
  "- Public API of a module -> `extract_module_interface`.",
  "- Type hierarchy -> `find_supertypes`/`find_subtypes`/`find_implementations`. Construction sites -> `find_instantiations`.",
  "- \"How does this codebase implement X?\" -> `find_symbol name=<X>` first; if it exists, study the existing implementation. If not, `find_symbol` for a sibling/analog, `describe_node` it, mirror its pattern.",
  "- Cross-file dependencies -> `trace_dependencies`. Cycles -> `find_cycles`. External packages -> `find_external_dependencies`.",
  "- Refactor planning -> `find_modularization_seams`, `analyze_coupling`.",
  "- LAST RESORT for orientation (only when search returned nothing) -> `get_file_map`/`get_module_map` with NO `path_prefix`. `codebase_stats` for high-level diagnostics.",
  "- Clusters/flows -> `clusters`, `cluster_members`, `find_flows`.",
  "",
  "Use `rg`/`grep` only for exact text matches the index doesn't cover (string literals, comments, config files) or to verify a codebrain finding. Do not use it to locate symbols, callers, or types -- codebrain answers those faster and with structure. If the index appears stale, re-ingest -- do not paper over it with ad-hoc workarounds.",
  "",
  "Read the `codebrain://usage` resource for the full per-tool workflow guide, parameter conventions, and anti-patterns.",
].join("\n");
const CODEBRAIN_USAGE_TEXT = [
  "# CodeBrain Usage",
  "",
  "All query tools (everything except `list_repositories`) are repository-scoped and require the `repo` parameter.",
  "",
  "## Self-Discovery Policy",
  "",
  "- **Always start with** `list_repositories` to find the correct `repo` string. Do not guess it from the working directory.",
  "- **Use MCP tools first** for semantic, symbol, reference, dependency, hierarchy, and architecture analysis.",
  "- **Use external text search (`rg`, `grep`)** as a precision and verification complement, or when index coverage may be stale.",
  "- If the index appears stale or inconsistent with the working tree, re-ingest rather than working around it with ad-hoc heuristics.",
  "",
  "## Workflows",
  "",
  "### 1. Concept discovery",
  "When you need to find where a feature lives but don't know exact names:",
  "- `semantic_search` with a 2-8 word technical phrase. Optional filters: `intent` (e.g., `business-logic`, `data-model`), `language`, `path_prefix`, `threshold`. Documentation chunks are filtered out unless `include_documentation: true`.",
  "- If you already know a partial identifier, prefer `find_symbol` -- faster and more precise.",
  "",
  "### 2. Symbol and reference lookups",
  "- `find_symbol` -- partial-name lookup ranked by match strength; supports `kind` and `file` filters.",
  "- `exact_symbol_search` -- exact identifier match for grep-like precision.",
  "- `find_references` -- lexical and call references. Defaults to resolved, high-confidence matches (`min_confidence` 0.55). Pass `include_unresolved: true` for heuristic-only matches; set `reference_kind` to filter to `call` / `member_call` / `type_reference` / `instantiation`.",
  "",
  "### 3. Control flow and impact",
  "- `find_call_graph` -- bounded forward (callees) or reverse (callers) graph, resolved edges only.",
  "- `find_impact` -- reverse-traverses confidence-scored edges. Returns \"likely\" (>=0.75) and \"possible\" (>=`min_confidence`) bands grouped by edge category.",
  "- `trace_dependencies` -- inbound/outbound/both walk across file boundaries up to `max_depth`. Pass `summary: true` for aggregated counts.",
  "",
  "### 4. Type hierarchies and interfaces",
  "- `find_supertypes` / `find_subtypes` -- transitive walk over `extends`/`implements` relationships.",
  "- `find_implementations` -- direct and transitive implementers/subclasses of an interface or abstract type.",
  "- `find_instantiations` -- where a `class`/`struct` is actually constructed.",
  "",
  "### 5. Architectural and subsystem overview",
  "- `get_file_map` -- per-file roles, summaries, and exported symbols under a `path_prefix`.",
  "- `get_intent` -- file summary plus per-chunk intent labels and line ranges. Use before editing a file you haven't read.",
  "- `get_module_map` -- directory and logical modules with role, dominant intent, and counts. Filter by `kind` (`directory` | `logical` | `all`) or `path_prefix`.",
  "- `codebase_stats` -- repo-level totals, language mix, intent distribution, symbol-kind counts.",
  "- `get_index_size` -- estimated storage and row counts.",
  "",
  "### 6. Clusters and execution flows",
  "- `clusters` -- named clusters with size, modularity, and granularity (`symbol` or `file`).",
  "- `cluster_members` -- weighted members of a cluster. Accepts cluster id, `cluster_key`, or name.",
  "- `find_flows` -- execution-flow memberships. Pass exactly one of `symbol` (lists flows that include the symbol) or `flow` (lists members of the flow). Flow selector accepts id, `flow_key`, or name.",
  "- `describe_node` -- unified description of a `file`, `symbol`, or `cluster`, including any linked doc_links prose.",
  "",
  "### 7. Refactoring and modularization",
  "- `analyze_coupling` -- afferent/efferent coupling and instability for a `path_prefix`, plus top cross-boundary file pairs.",
  "- `extract_module_interface` -- the public surface of a directory (exports actually consumed externally). Pass `include_unused: true` to also list exported-but-unused symbols.",
  "- `find_modularization_seams` -- extraction plan: required interfaces, dependencies to inject, and seam edges to cut.",
  "- `find_cycles` -- persisted dependency cycles, optionally filtered by `path_prefix`.",
  "- `find_external_dependencies` -- third-party packages summarized by usage, with optional `package_name` to drill into consumers. Stdlib excluded unless `include_stdlib: true`.",
  "",
  "### 8. Index management",
  "- `delete_index` -- destructive; permanently removes all indexed data for a repo. Requires `confirm: true`. Do not call without explicit user instruction.",
  "",
  "## Anti-Patterns",
  "",
  "- **Do not call query tools without a `repo`.** Run `list_repositories` first.",
  "- **Do not loop `semantic_search` with slightly different phrasings.** If two attempts miss, switch to `find_symbol`/`exact_symbol_search` or `rg`.",
  "- **Do not bypass stale-index symptoms with per-tool workarounds.** Re-ingest first.",
  "- **Do not call `delete_index` to \"clean up\".** It is destructive and requires explicit user instruction.",
  "- **Do not assume `find_references` includes unresolved heuristic matches.** They are filtered by default; set `include_unresolved: true` if you specifically want them.",
].join("\n");

/**
 * @brief Registers usage documentation as an MCP resource.
 * @param server MCP server instance.
 * @returns Void.
 */
export function registerResources(server: McpServer): void {
  server.registerResource(
    "usage",
    CODEBRAIN_USAGE_URI,
    {
      title: "CodeBrain Usage",
      description: "Read this first for the recommended CodeBrain workflow and search strategy.",
      mimeType: "text/markdown",
    },
    async (uri) => ({
      contents: [
        {
          uri: uri.toString(),
          mimeType: "text/markdown",
          text: CODEBRAIN_USAGE_TEXT,
        },
      ],
    }),
  );
}
